apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-yzmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-yzmn
    app.kubernetes.io/part-of: test-app-hvvr
  name: test-component-yzmn
  namespace: build-e2e-hacbs-bbak
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-yzmn
status:
  loadBalancer: {}
